host: localhost

debug: False
trace: False

ratelimit: 2000000 #KiloBytes
codec: opus #? flac, opus, mp3, aac, alac, best
restrictfilenames: True



db:
  engine: postgresql # Postgresql, sqlite, mysql, mariadb
  host: localhost
  port: 5432
  db: youtube
  user: default
  password: default
  timezone: America/Los_Angeles
